import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Skip waiting and claim clients immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      // Clean up old caches
      caches.keys().then(cacheNames => {
        return Promise.all(
          cacheNames.map(cacheName => {
            // Delete old workbox caches
            if (cacheName.startsWith('workbox-precache') && !cacheName.includes(self.__WB_REVISION)) {
              return caches.delete(cacheName);
            }
          })
        );
      }),
      // Claim all clients immediately
      clients.claim()
    ])
  );
});

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Add default handler for navigation requests (SPA support)
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'navigations',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
    // Fallback to index.html for offline navigation
    networkTimeoutSeconds: 3,
  })
);

// Add a catch-all route for any requests not handled by other routes
registerRoute(
  // Match all requests
  ({ request }) => request.method === 'GET',
  new NetworkFirst({
    cacheName: 'runtime-cache',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache video files
registerRoute(
  ({ request }) => request.url.endsWith('.mp4'),
  new CacheFirst({
    cacheName: 'video-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache drill images
registerRoute(
  ({ request, url }) => request.destination === 'image' && url.pathname.includes('/drill/'),
  new CacheFirst({
    cacheName: 'drill-images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200, // Cache up to 200 drill images
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache music images
registerRoute(
  ({ request, url }) => request.destination === 'image' && url.pathname.includes('/music/'),
  new CacheFirst({
    cacheName: 'music-images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 300, // Cache up to 300 music images
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache audio files (MP3s for movements)
registerRoute(
  ({ request, url }) => request.url.endsWith('.mp3') || request.url.endsWith('.m4a'),
  new CacheFirst({
    cacheName: 'audio-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10, // Cache up to 10 audio files
        maxAgeSeconds: 90 * 24 * 60 * 60, // 90 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200, 206], // Include 206 for partial content (range requests)
      }),
    ],
  })
);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 365 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);
